name: Build Custom Linux Distro

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y debootstrap grub-pc-bin grub-efi-amd64-bin xorriso mtools

    - name: Create Root Filesystem
      run: |
        mkdir -p custom_distro/chroot
        sudo debootstrap --arch=amd64 focal custom_distro/chroot http://archive.ubuntu.com/ubuntu/
        sudo mount --bind /dev custom_distro/chroot/dev
        sudo mount --bind /proc custom_distro/chroot/proc
        sudo mount --bind /sys custom_distro/chroot/sys

    - name: Configure the Chroot Environment
      run: |
        sudo cp /etc/resolv.conf custom_distro/chroot/etc/
        sudo chroot custom_distro/chroot /bin/bash -c "
          apt-get update &&
          apt-get install -y ubuntu-desktop gnome-shell gdm3 &&
          apt-get install -y python3 python3-tk &&
          echo 'python3 /hello_world.py' >> /etc/rc.local &&
          chmod +x /etc/rc.local
        "

    - name: Add Custom Python Script
      run: |
        echo 'import tkinter as tk' > custom_distro/chroot/hello_world.py
        echo 'root = tk.Tk()' >> custom_distro/chroot/hello_world.py
        echo 'root.geometry("600x400")' >> custom_distro/chroot/hello_world.py
        echo 'label = tk.Label(root, text="Hello, World!")' >> custom_distro/chroot/hello_world.py
        echo 'label.pack(pady=20)' >> custom_distro/chroot/hello_world.py
        echo 'root.mainloop()' >> custom_distro/chroot/hello_world.py

    - name: Configure GRUB for BIOS and UEFI
      run: |
        sudo chroot custom_distro/chroot /bin/bash -c "
          apt-get update &&
          apt-get install -y grub-pc grub-efi-amd64 &&
          mkdir -p /boot/grub &&
          grub-install --target=i386-pc --boot-directory=/boot /dev/sda &&
          grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=ubuntu
        "

    - name: Create Bootable ISO with grub-mkrescue
      run: |
        sudo mkdir -p custom_distro/chroot/boot/grub
        sudo cp -r custom_distro/chroot/boot custom_distro/iso_boot

        # Create the ISO using grub-mkrescue
        sudo grub-mkrescue -o /tmp/custom_linux.iso custom_distro/iso_boot

    - name: Upload ISO as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: custom-linux-iso
        path: /tmp/custom_linux.iso
