name: Build Custom Distro

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Build Environment
      run: |
        sudo apt update
        sudo apt install -y debootstrap mkisofs

    - name: Bootstrap the Base System
      run: |
        mkdir -p $HOME/custom-distro/rootfs
        sudo debootstrap --variant=buildd --arch=amd64 focal $HOME/custom-distro/rootfs http://archive.ubuntu.com/ubuntu/

    - name: Chroot and Customize System
      run: |
        sudo mount --bind /proc $HOME/custom-distro/rootfs/proc
        sudo mount --bind /sys $HOME/custom-distro/rootfs/sys
        sudo mount --bind /dev $HOME/custom-distro/rootfs/dev
        sudo mount --bind /dev/pts $HOME/custom-distro/rootfs/dev/pts
        sudo chroot $HOME/custom-distro/rootfs /bin/bash <<EOF
        # Add necessary repositories
        echo "deb http://archive.ubuntu.com/ubuntu focal main universe" > /etc/apt/sources.list
        apt update
        apt install -y openbox xterm
        # Create and configure GUI script
        echo '#!/bin/sh' > /root/hello-world.sh
        echo 'xterm -bg white -fg black -e "echo Hello, World!; read -p \"Press Enter to exit...\"" &' >> /root/hello-world.sh
        mkdir -p /root/.config/openbox
        echo '#!/bin/sh' > /root/.config/openbox/autostart
        echo 'xterm -bg white -fg black -e /root/hello-world.sh &' >> /root/.config/openbox/autostart
        echo 'exec openbox --replace' >> /root/.config/openbox/autostart
        chmod +x /root/hello-world.sh
        chmod +x /root/.config/openbox/autostart
        EOF

    - name: Unmount Filesystems
      run: |
        sudo umount $HOME/custom-distro/rootfs/proc
        sudo umount $HOME/custom-distro/rootfs/sys
        sudo umount $HOME/custom-distro/rootfs/dev/pts
        sudo umount $HOME/custom-distro/rootfs/dev

    - name: Create ISO Image
      run: |
        sudo mkisofs -o $HOME/custom-distro.iso -b isolinux.bin -c boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table $HOME/custom-distro

    - name: Upload ISO as artifact
      uses: actions/upload-artifact@v3
      with:
        name: custom-distro-iso
        path: $HOME/custom-distro.iso
