name: Build Ubuntu ISO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git squashfs-tools grub-pc-bin xorriso debootstrap

      - name: Create root filesystem
        run: |
          mkdir -p ~/ubuntu_root
          sudo debootstrap --arch=amd64 focal ~/ubuntu_root http://archive.ubuntu.com/ubuntu/

      - name: Configure and install packages
        run: |
          sudo mount --bind /dev ~/ubuntu_root/dev
          sudo mount --bind /proc ~/ubuntu_root/proc
          sudo mount --bind /sys ~/ubuntu_root/sys
          sudo chroot ~/ubuntu_root /bin/bash -c "apt-get update && apt-get install -y grub-pc-bin grub-efi-amd64"
          sudo chroot ~/ubuntu_root /bin/bash -c "update-grub"
          sudo umount ~/ubuntu_root/dev
          sudo umount ~/ubuntu_root/proc
          sudo umount ~/ubuntu_root/sys

      - name: Build SquashFS image
        run: |
          mksquashfs ~/ubuntu_root ~/ubuntu_root.squashfs -e boot

      - name: Prepare ISO directory
        run: |
          mkdir -p ~/iso/boot/grub
          cp -r /usr/lib/grub/x86_64-efi/* ~/iso/boot/grub/
          cp ~/ubuntu_root.squashfs ~/iso/



      - name: Build ISO
        run: |
          xorriso -as mkisofs \
            -r -V 'Custom Ubuntu ISO' \
            -o ~/ubuntu_custom.iso \
            -b boot/grub/i386-pc/eltorito.img \
            -c boot.catalog \
            -no-emul-boot \
            -boot-load-size 4 \
            -boot-info-table \
            ~/iso



      - name: Upload ISO artifact
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-custom-iso
          path: ~/ubuntu_custom.iso
