name: Build Custom Ubuntu ISO

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_iso:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y binutils debootstrap squashfs-tools xorriso grub-pc-bin grub-efi-amd64-bin mtools dosfstools unzip

    - name: Set up chroot environment
      run: |
        sudo sh build.sh
        ls

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:

          name: ISO

          path: custom-ubuntu.iso
            

  
